<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'yiisoft/yii2-app-basic',
        'dev' => true,
    ),
    'versions' => array(
        '2amigos/yii2-chartjs-widget' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../2amigos/yii2-chartjs-widget',
            'aliases' => array(),
            'reference' => 'b144a4ebd923872a7263c980f8afe2e212378275',
            'dev_requirement' => false,
        ),
        '2amigos/yii2-date-picker-widget' => array(
            'pretty_version' => '1.0.7',
            'version' => '1.0.7.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../2amigos/yii2-date-picker-widget',
            'aliases' => array(),
            'reference' => 'd09c2444e8c2329e38528bba77002dd65186c1ff',
            'dev_requirement' => false,
        ),
        'almasaeed2010/adminlte' => array(
            'pretty_version' => 'v2.4.18',
            'version' => '2.4.18.0',
            'type' => 'template',
            'install_path' => __DIR__ . '/../almasaeed2010/adminlte',
            'aliases' => array(),
            'reference' => 'e7ffa67a4649dc08d2018708a38604a6c0a02ab6',
            'dev_requirement' => false,
        ),
        'behat/gherkin' => array(
            'pretty_version' => 'v4.7.3',
            'version' => '4.7.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(),
            'reference' => 'd5ae4616aeaa91daadbfb8446d9d17aae8d43cf7',
            'dev_requirement' => true,
        ),
        'bower-asset/ace-builds' => array(
            'pretty_version' => 'v1.15.3',
            'version' => '1.15.3.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/ace-builds',
            'aliases' => array(),
            'reference' => 'a6f05db4a359a66152afc29b6382caeb09a84cbd',
            'dev_requirement' => false,
        ),
        'bower-asset/bootstrap' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/bootstrap',
            'aliases' => array(),
            'reference' => '68b0d231a13201eb14acd3dc84e51543d16e5f7e',
            'dev_requirement' => false,
        ),
        'bower-asset/bootstrap-datepicker' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/bootstrap-datepicker',
            'aliases' => array(),
            'reference' => 'd364be5b066b38f3675a5a1dc174ce1ab1f3360e',
            'dev_requirement' => false,
        ),
        'bower-asset/chartjs' => array(
            'pretty_version' => 'v2.9.4',
            'version' => '2.9.4.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/chartjs',
            'aliases' => array(),
            'reference' => '9bd4cf82fda9f50a5fb50b72843e06ab88124278',
            'dev_requirement' => false,
        ),
        'bower-asset/fullcalendar' => array(
            'pretty_version' => 'v4.4.3',
            'version' => '4.4.3.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/fullcalendar',
            'aliases' => array(),
            'reference' => '71f15cc03f43f37943b91afb5b74f5cbc892c486',
            'dev_requirement' => false,
        ),
        'bower-asset/fullcalendar-scheduler' => array(
            'pretty_version' => 'v4.4.3',
            'version' => '4.4.3.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/fullcalendar-scheduler',
            'aliases' => array(),
            'reference' => 'af79dec4871ed3b1cd5133c4b6021113e6795100',
            'dev_requirement' => false,
        ),
        'bower-asset/inputmask' => array(
            'pretty_version' => '3.3.11',
            'version' => '3.3.11.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/inputmask',
            'aliases' => array(),
            'reference' => '5e670ad62f50c738388d4dcec78d2888505ad77b',
            'dev_requirement' => false,
        ),
        'bower-asset/jquery' => array(
            'pretty_version' => '3.6.4',
            'version' => '3.6.4.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery',
            'aliases' => array(),
            'reference' => '91ef2d8836342875f2519b5815197ea0f23613cf',
            'dev_requirement' => false,
        ),
        'bower-asset/jquery-ui' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery-ui',
            'aliases' => array(),
            'reference' => '44ecf3794cc56b65954cc19737234a3119d036cc',
            'dev_requirement' => false,
        ),
        'bower-asset/punycode' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/punycode',
            'aliases' => array(),
            'reference' => '38c8d3131a82567bfef18da09f7f4db68c84f8a3',
            'dev_requirement' => false,
        ),
        'bower-asset/sweetalert' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/sweetalert',
            'aliases' => array(),
            'reference' => '3b9d8eb90268e0b1f8f58b2eba240631df0ad18f',
            'dev_requirement' => false,
        ),
        'bower-asset/toastr' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/toastr',
            'aliases' => array(),
            'reference' => 'e648a870a60103bbc3986c1fe2b2de86ea4a9569',
            'dev_requirement' => false,
        ),
        'bower-asset/typeahead.js' => array(
            'pretty_version' => 'v0.11.1',
            'version' => '0.11.1.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/typeahead.js',
            'aliases' => array(),
            'reference' => '588440f66559714280628a4f9799f0c4eb880a4a',
            'dev_requirement' => true,
        ),
        'bower-asset/yii2-pjax' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/yii2-pjax',
            'aliases' => array(),
            'reference' => 'a9298d57da63d14a950f1b94366a864bc62264fb',
            'dev_requirement' => false,
        ),
        'cebe/markdown' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cebe/markdown',
            'aliases' => array(),
            'reference' => '9bac5e971dd391e2802dca5400bbeacbaea9eb86',
            'dev_requirement' => false,
        ),
        'cebe/yii2-gravatar' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../cebe/yii2-gravatar/cebe/gravatar',
            'aliases' => array(),
            'reference' => 'c9c01bd14c9bdee9e5ae1ef1aad23f80c182c057',
            'dev_requirement' => false,
        ),
        'codeception/base' => array(
            'pretty_version' => '2.5.6',
            'version' => '2.5.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/base',
            'aliases' => array(),
            'reference' => 'aace5bab5593c93d8473b620f70754135a1eb4f0',
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'pretty_version' => '6.1.3',
            'version' => '6.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/phpunit-wrapper',
            'aliases' => array(),
            'reference' => 'bc6e12f2e6990d22b55c63fbbb3a6f86292b945b',
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'codeception/specify' => array(
            'pretty_version' => '0.4.6',
            'version' => '0.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/specify',
            'aliases' => array(),
            'reference' => '21b586f503ca444aa519dd9cafb32f113a05f286',
            'dev_requirement' => true,
        ),
        'codeception/stub' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'reference' => 'f50bc271f392a2836ff80690ce0c058efe1ae03e',
            'dev_requirement' => true,
        ),
        'codeception/verify' => array(
            'pretty_version' => '0.3.3',
            'version' => '0.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/verify',
            'aliases' => array(),
            'reference' => '5d649dda453cd814dadc4bb053060cd2c6bb4b4c',
            'dev_requirement' => true,
        ),
        'dektrium/yii2-rbac' => array(
            'pretty_version' => '1.0.0-alpha',
            'version' => '1.0.0.0-alpha',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../dektrium/yii2-rbac',
            'aliases' => array(),
            'reference' => '0943e66c450132b306584a37caefc2aa04258372',
            'dev_requirement' => false,
        ),
        'dektrium/yii2-user' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../dektrium/yii2-user',
            'aliases' => array(
                0 => '0.9.x-dev',
            ),
            'reference' => '761ae89f188bfa87eb72a9d5fe0cff015a9451e1',
            'dev_requirement' => false,
        ),
        'dmstr/yii2-adminlte-asset' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../dmstr/yii2-adminlte-asset',
            'aliases' => array(),
            'reference' => 'c96336e1960ebc6c1e72487a7c6ca1a1589519fe',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => '8e884e78f9f0eb1329e445619e04456e64d8051d',
            'dev_requirement' => true,
        ),
        'ergebnis/faker' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.9.2',
            ),
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.9.2',
            'version' => '1.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'reference' => '84220cf137a9344acffb10374e781fed785ff307',
            'dev_requirement' => true,
        ),
        'fortawesome/font-awesome' => array(
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fortawesome/font-awesome',
            'aliases' => array(),
            'reference' => 'a8386aae19e200ddb0f6845b5feeee5eb7013687',
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.9.2',
            ),
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'e4490cabc77465aaee90b20cfc9a770f8c04be6b',
            'dev_requirement' => true,
        ),
        'kartik-v/bootstrap-checkbox-x' => array(
            'pretty_version' => 'v1.5.7',
            'version' => '1.5.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-checkbox-x',
            'aliases' => array(),
            'reference' => '1060db69ad2519a2b36cf5e0e28f542c21135672',
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-fileinput' => array(
            'pretty_version' => 'v5.5.2',
            'version' => '5.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-fileinput',
            'aliases' => array(),
            'reference' => '35c29cd9fd5bc47eae5238feaabee95b2d7efe3c',
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-popover-x' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-popover-x',
            'aliases' => array(),
            'reference' => '36c382739c4f61ee44263a426e6447abed5ff0bd',
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-star-rating' => array(
            'pretty_version' => 'v4.1.2',
            'version' => '4.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-star-rating',
            'aliases' => array(),
            'reference' => 'c301efed4c82e9d5f11a0845ae428ba60931b44e',
            'dev_requirement' => false,
        ),
        'kartik-v/dependent-dropdown' => array(
            'pretty_version' => 'v1.4.9',
            'version' => '1.4.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/dependent-dropdown',
            'aliases' => array(),
            'reference' => '54a8806002ee21b744508a2edb95ed01d35c6cf9',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-checkbox-x' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-checkbox-x',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '0ac0c009d8f6ba2f9f31d0db12a02581c1e698b4',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-date-range' => array(
            'pretty_version' => 'v1.7.3',
            'version' => '1.7.3.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-date-range',
            'aliases' => array(),
            'reference' => '7d80d6e2598e252487fe1acf911b8cb43f45e3b1',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dialog' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dialog',
            'aliases' => array(),
            'reference' => '510c3a35ffe79987cde9a9366cedbff545fd92d4',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dynagrid' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dynagrid',
            'aliases' => array(),
            'reference' => '02956ed5c753010e700bfdb63e67ef41606e1c2d',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-editable' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-editable',
            'aliases' => array(
                0 => '1.8.x-dev',
            ),
            'reference' => 'ae4cc2384e667ba9dfe8bfb0098716caeb2500a8',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-export' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-export',
            'aliases' => array(
                0 => '1.4.x-dev',
            ),
            'reference' => 'ec1040cd1b8588a3947ec9d22c29a44047eadd73',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-field-range' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-field-range',
            'aliases' => array(
                0 => '1.3.x-dev',
            ),
            'reference' => '8a18edb343b3beb96ddc86e4a06aee28be160787',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-grid' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-grid',
            'aliases' => array(
                0 => '3.5.x-dev',
            ),
            'reference' => 'c407f8e09732e5965278c63643f882c431daa298',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-helpers' => array(
            'pretty_version' => 'v1.3.9',
            'version' => '1.3.9.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-helpers',
            'aliases' => array(),
            'reference' => '0bec7a97bf9d0293d96be5c496fe9654c4dec94b',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-krajee-base' => array(
            'pretty_version' => 'v3.0.5',
            'version' => '3.0.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-krajee-base',
            'aliases' => array(),
            'reference' => '5c095126d1be47e0bb1f92779b7dc099f6feae31',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-mpdf' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-mpdf',
            'aliases' => array(),
            'reference' => '7ea3a5f9bcf5bcf6d681bd82cbe843c356d1428c',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-popover-x' => array(
            'pretty_version' => 'v1.3.5',
            'version' => '1.3.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-popover-x',
            'aliases' => array(),
            'reference' => 'b0320d1315bbfce31ec8907882c6f4abed223a28',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-sortable' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-sortable',
            'aliases' => array(),
            'reference' => 'a6f9a9adb873d6345de92bbe5e436ac1a1db30bc',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-activeform' => array(
            'pretty_version' => 'v1.6.2',
            'version' => '1.6.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-activeform',
            'aliases' => array(),
            'reference' => '98dbf789c9f71a35c76a8c2b667e86815ae51ac1',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-affix' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-affix',
            'aliases' => array(),
            'reference' => '2184119bfa518c285406156f744769b13b861712',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-alert' => array(
            'pretty_version' => 'v1.1.5',
            'version' => '1.1.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-alert',
            'aliases' => array(),
            'reference' => '6a45d7dc294eecd578cf8cb9acb671d1cafa0727',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-colorinput' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-colorinput',
            'aliases' => array(),
            'reference' => 'e35e6c7615a735b65557d6c38d112b77e2628c69',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datepicker' => array(
            'pretty_version' => 'v1.4.8',
            'version' => '1.4.8.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datepicker',
            'aliases' => array(),
            'reference' => 'f5f8b396cf03d4a383aad5e7b338f8cb065abf66',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datetimepicker' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datetimepicker',
            'aliases' => array(),
            'reference' => '85b22d38553ca207f86be198f37e6531347e9a23',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-depdrop' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-depdrop',
            'aliases' => array(),
            'reference' => 'ea347e3793fbd8273cc9bd1eb94c4b32bb55d318',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-fileinput' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-fileinput',
            'aliases' => array(),
            'reference' => 'b5500b6855526837154694c2afab8dbc3afc8abd',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-growl' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-growl',
            'aliases' => array(),
            'reference' => '37e8f9f10d3bc9d71f3ef64c4aaa0e2fc83dd5dc',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rangeinput' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rangeinput',
            'aliases' => array(),
            'reference' => 'dd9019bab7e5bf570a02870d9e74387891bbdb32',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rating' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rating',
            'aliases' => array(),
            'reference' => 'd3d7249490044f80e65f8f3938191f39a76586b2',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-select2' => array(
            'pretty_version' => 'v2.2.4',
            'version' => '2.2.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-select2',
            'aliases' => array(),
            'reference' => 'f74f2cfbd5b4628ea578735890c39f9a8e4ed062',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-sidenav' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-sidenav',
            'aliases' => array(),
            'reference' => '87e9c815624aa966d70bb4507b3d53c158db0d43',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-spinner' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-spinner',
            'aliases' => array(),
            'reference' => 'eb10dad17a107bf14f173c99994770ca23c548a6',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-switchinput' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-switchinput',
            'aliases' => array(),
            'reference' => '7d8ee999d79bcdc1601da5cd59439ac7eb1f5ea6',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-timepicker' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-timepicker',
            'aliases' => array(),
            'reference' => '680aec2d79846e926c072da455cf6f33e1c3bb12',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-touchspin' => array(
            'pretty_version' => 'v1.2.4',
            'version' => '1.2.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-touchspin',
            'aliases' => array(),
            'reference' => '1eec4c3f3a8bf9a170e1e0682c2c89f2929d65e9',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-typeahead' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-typeahead',
            'aliases' => array(),
            'reference' => '7b7041a3cbbeb2db0a608e9f6c9b3f4f63b0069d',
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widgets' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widgets',
            'aliases' => array(),
            'reference' => 'e5a030d700243a90eccf96a070380bd3b76e17a3',
            'dev_requirement' => false,
        ),
        'lavrentiev/yii2-toastr' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../lavrentiev/yii2-toastr',
            'aliases' => array(),
            'reference' => 'a5392f09c64285fc15d5be17bb23ae959b3b382d',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => 'c3131244e29c08d44fefb49e0dd35021e9e39dd2',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => '44bb1ab01811116f01fe216ab37d921dccc6c10d',
            'dev_requirement' => false,
        ),
        'mdmsoft/yii2-admin' => array(
            'pretty_version' => '2.12',
            'version' => '2.12.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../mdmsoft/yii2-admin',
            'aliases' => array(),
            'reference' => '10e526fbcf6350ed4cc9ba6298f887d611685367',
            'dev_requirement' => false,
        ),
        'miloschuman/yii2-highcharts-widget' => array(
            'pretty_version' => 'v5.0.2',
            'version' => '5.0.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../miloschuman/yii2-highcharts-widget',
            'aliases' => array(),
            'reference' => '911c8bb86b6343b1758bca76cce58339092f2926',
            'dev_requirement' => false,
        ),
        'moonlandsoft/yii2-phpexcel' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../moonlandsoft/yii2-phpexcel',
            'aliases' => array(),
            'reference' => 'e0614787a41a9e7e1c9ab3b707ce54c256461d7f',
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.1.6',
            'version' => '8.1.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'reference' => '146c7c1dfd21c826b9d5bbfe3c15e52fd933c90f',
            'dev_requirement' => false,
        ),
        'mpdf/psr-log-aware-trait' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/psr-log-aware-trait',
            'aliases' => array(),
            'reference' => '7a077416e8f39eb626dee4246e0af99dd9ace275',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.21',
            'version' => '2.0.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '96c132c7f2f7bc3230723b66e89f8f150b29d5ae',
            'dev_requirement' => false,
        ),
        'philippfrenzel/yii2fullcalendar' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../philippfrenzel/yii2fullcalendar',
            'aliases' => array(),
            'reference' => '53c8b2f524c5f5d85bd30f6ed7ba34b563479782',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => 'bf329f6c1aadea3299f08ee804682b7c45b326a2',
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '9c977708995954784726e25d0cd1dddf4e65b0f7',
            'dev_requirement' => true,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v5.2.28',
            'version' => '5.2.28.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'acba50393dd03da69a50226c139722af8b153b11',
            'dev_requirement' => false,
        ),
        'phpoffice/phpexcel' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpexcel',
            'aliases' => array(),
            'reference' => '1441011fb7ecdd8cc689878f54f8b58a6805f870',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => '0c1346a1956347590b7db09533966307d20cb7cc',
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'dev_requirement' => true,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'ef7b2f56815df854e66ceaee8ebe9393ae36a40d',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'reference' => '1ce90ba27c42e4e44e6d8458241466380b51fa16',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '5.7.27',
            'version' => '5.7.27.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => 'b7803aeca3ccb99ad0a506fa80b64cd6a56bbc0c',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'reference' => 'a23b761686d50a560cc56233b9ecf49597cc9118',
            'dev_requirement' => true,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'ptrnov/yii2-scheduler-fullcalendar' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../ptrnov/yii2-scheduler-fullcalendar',
            'aliases' => array(),
            'reference' => '218bef1068b23dfd973c2adf846a955cc5fff03f',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => true,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '3.9.7',
            'version' => '3.9.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'dc75aa439eb4c1b77f5379fd958b3dc0e6014178',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.9.7',
            ),
        ),
        'rmrevin/yii2-fontawesome' => array(
            'pretty_version' => '2.17.1',
            'version' => '2.17.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../rmrevin/yii2-fontawesome',
            'aliases' => array(),
            'reference' => '65ce306da864f4d558348aeba040ed7876878090',
            'dev_requirement' => false,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => '1de8cd5c010cb153fcd68b8d0f64606f523f7619',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '7f066a26a962dbe58ddea9f72a4e82874a3975a4',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => '5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => 'ce474bdd1a34744d7ac5d6aad3a46d48d9bac4c4',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => 'bc37d50fea7d017d3d340f230811c9f1d7280af4',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => '1311872ac850040a79c3c058bea3e22d0f09cbb7',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => '2c3ba150cbec723aa057506e73a8d33bdb286c9a',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => 'ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'dev_requirement' => true,
        ),
        'select2/select2' => array(
            'pretty_version' => '4.0.13',
            'version' => '4.0.13.0',
            'type' => 'component',
            'install_path' => __DIR__ . '/../select2/select2',
            'aliases' => array(),
            'reference' => '45f2b83ceed5231afa7b3d5b12b58ad335edd82e',
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.3.7',
            'version' => '2.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'reference' => 'bccc892d5fa1f48c43f8ba7db5ed4ba6f30c8c05',
            'dev_requirement' => false,
        ),
        'slavkovrn/yii2-prettyphoto' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../slavkovrn/yii2-prettyphoto',
            'aliases' => array(),
            'reference' => '1fa54eec7e302121501133d7c0e252c5cd71d72e',
            'dev_requirement' => false,
        ),
        'soundasleep/html2text' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../soundasleep/html2text',
            'aliases' => array(),
            'reference' => 'cdb89f6ffa2c4cc78f8ed9ea6ee0594a9133ccad',
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '181b89f18a90f8925ef805f950d47a7190e9b950',
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'reference' => '9590bd3d3f9fa2f28d34b713ed4765a8cc8ad15c',
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'a10b1da6fc93080c180bba7219b5ff5b7518fe81',
            'dev_requirement' => true,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'da3d9da2ce0026771f5fe64cb332158f1bd2bc33',
            'dev_requirement' => true,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => 'ab42889de57fdfcfcc0759ab102e2fd4ea72dcae',
            'dev_requirement' => true,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'reference' => 'ef97bcfbae5b384b4ca6c8d57b617722f15241a6',
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '31fde73757b6bad247c54597beef974919ec6860',
            'dev_requirement' => true,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => 'b6b6ad3db3edb1b4b1c1896b1975fb684994de6e',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => 'aed596913b70fae57be53d86faa2e9ef85a2297b',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'b5f7b932ee6fa802fc792eabd77c4c88084517ce',
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '88289caa3c166321883f67fe5130188ebbb47094',
            'dev_requirement' => true,
        ),
        'thamtech/yii2-uuid' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../thamtech/yii2-uuid',
            'aliases' => array(),
            'reference' => 'ec6dbfcb9a3236a0ef9ce68c95fe1b6519a07886',
            'dev_requirement' => false,
        ),
        'trntv/yii2-aceeditor' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../trntv/yii2-aceeditor',
            'aliases' => array(),
            'reference' => '807ce92d46375308b9ca55d4ceeda12ba632dfae',
            'dev_requirement' => false,
        ),
        'unclead/yii2-multiple-input' => array(
            'pretty_version' => '2.27.0',
            'version' => '2.27.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../unclead/yii2-multiple-input',
            'aliases' => array(),
            'reference' => 'c63151f832e7184f8fdf672e9426b0c6159fb2c7',
            'dev_requirement' => false,
        ),
        'vova07/yii2-imperavi-widget' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../vova07/yii2-imperavi-widget',
            'aliases' => array(),
            'reference' => 'c4fe4a9f64a4c53d9686c80b8744e2c1366184e5',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => 'bafc69caeb4d49c39fd0779086c03a3738cbb389',
            'dev_requirement' => true,
        ),
        'yii2learning/yii2-chart-builder' => array(
            'pretty_version' => '0.1.4',
            'version' => '0.1.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yii2learning/yii2-chart-builder',
            'aliases' => array(),
            'reference' => 'ec68f8c7a24e77cc8b709053e3dbb93a63022a10',
            'dev_requirement' => false,
        ),
        'yii2mod/yii2-sweet-alert' => array(
            'pretty_version' => '1.3',
            'version' => '1.3.0.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yii2mod/yii2-sweet-alert',
            'aliases' => array(),
            'reference' => 'dce46828aa96f8f2490204cb02ccc9ae1f27a400',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2' => array(
            'pretty_version' => '2.0.48.1',
            'version' => '2.0.48.1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yiisoft/yii2',
            'aliases' => array(),
            'reference' => 'de92f154eefe322fc1b1b2a52cce46677441ced4',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-app-basic' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-authclient' => array(
            'pretty_version' => '2.2.14',
            'version' => '2.2.14.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-authclient',
            'aliases' => array(),
            'reference' => '6bd4b4efc60db2b31bb957a473442900c704857e',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap',
            'aliases' => array(),
            'reference' => '83d144f4089adaa7064ad60dc4c1436daa2eb30e',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-composer' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../yiisoft/yii2-composer',
            'aliases' => array(),
            'reference' => '94bb3f66e779e2774f8776d6e1bdeab402940510',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-debug' => array(
            'pretty_version' => '2.0.14',
            'version' => '2.0.14.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-debug',
            'aliases' => array(),
            'reference' => 'dc5a4a8529de1a41dbb037dbabf1f3f93002f21d',
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-faker' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-faker',
            'aliases' => array(),
            'reference' => '8c361657143bfaea58ff7dcc9bf51f1991a46f5d',
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-gii' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-gii',
            'aliases' => array(),
            'reference' => 'c02adc552bcf3a0ef6f3694a9dcbf209f4885ab1',
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-httpclient' => array(
            'pretty_version' => '2.0.15',
            'version' => '2.0.15.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-httpclient',
            'aliases' => array(),
            'reference' => '5a8350e15f2db3555ba52830c9c701587c136e87',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-jui' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-jui',
            'aliases' => array(),
            'reference' => 'ce45c16d4fbbe7d1c516d8d0e8311e07f6138eed',
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-swiftmailer' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-swiftmailer',
            'aliases' => array(),
            'reference' => '8a03a62cbcb82e7697d3002eb43a8d2637f566ec',
            'dev_requirement' => false,
        ),
        'zyx/zyx-phpmailer' => array(
            'pretty_version' => '0.9.4',
            'version' => '0.9.4.0',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../zyx/zyx-phpmailer',
            'aliases' => array(),
            'reference' => 'bfa2d987af3211c2dc81cc544893c85204f7781b',
            'dev_requirement' => false,
        ),
    ),
);
